# Generated by Django 3.2 on 2022-02-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='_file',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
